### ISSUE TITLE
Using {% include %} in markdown article.

### ISSUE THREAD

**Issue by ajacombs** [joachimneu/pelican-jinja2content#3]
I am attempting to use the `include` jinja2 tag in an article, but I'm not sure exactly what syntax is meant to be used, or what content is able to be included.

I am attempting to include the content of one article, inside another article. I have two files, `article.md` and `sidebar.md`. `article.md` has a jinja2 tag, to include `sidebar.md`.

Syntaxes I have tried:
- `{% include 'sidebar.md' %}`
- `{% include 'sidebar.html' %}`
- `{% include '{filename}sidebar.md' %}` _(as per the [Pelican intra-site linking syntax](http://docs.getpelican.com/en/3.5.0/content.html#linking-to-internal-content))_
- `{% include '../output/sidebar.html' %}`

All give an error on generation of:

> ERROR: Could not process ./article.md
> | /output/sidebar.md

Any pointers you could give would be much appreciated.

It might be a good idea to flesh out the documentation to give examples of various use cases.

**Comment by joachimneu** [comment]
I am not sure, whether it's possible to include other content such as articles from within articles... It might be possible by adding some more loaders (cf. https://github.com/joachimneu/pelican-jinja2content/blob/f73ef9b1ef1ee1f56c80757b4190b53f8cd607d1/jinja2content.py#L15), not only for the theme's `templates` directory?

Here is the type of use case I had in mind:

For example, I often include videos in my articles. Rather than embedding raw HTML snippets, I put a file `includes/videos.html` in my theme's `templates` directory with the following content:

```
{% macro youtube(id, params) %}
    some html snippet using {{ id }} and {{ params }}
{% endmacro %}

{% macro vimeo(id, params) %}
    some other html snippet using {{ id }} and {{ params }}
{% endmacro %}
```

And then in my articles I can use the following:

```
{% import 'includes/videos.html' as videos %}
{{ videos.youtube('Video-ID') }}
```

**Comment by MelleB** [comment]
What works for me is  

```
{% include '_sidebar.html' %}
```

with `_sidebar.html` being a file in my `templates` directory.

For me, being able to use this feature was the reason to install this plugin. Maybe it's a good idea to mention this example in the README.

**Comment by naarkhoo** [comment]
is there any other solution @MelleB  did not work for me.

**Comment by MartinThoma** [comment]
See also: https://github.com/getpelican/pelican/issues/1902

**Comment by joachimneu** [comment]
I close this because the repository is currently unmaintained. Please check out [the `jinja2content` plugin shipped with `pelican-plugins`](https://github.com/getpelican/pelican-plugins/tree/master/jinja2content).
